version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "https://github.com/luizmb/FP.git"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
