retain_public: true
disable_unused_import_analysis: true
retain_files:
  - Tests/**

targets:
  - Calculus
  - Math
  - MathOperators
  - RealNumber
  - RungeKutta
  - SwiftCalx
  - CalculusTests
  - MathOperatorsTests
  - MathTests
  - RealNumberTests
  - RungeKuttaTests
